#!/data/data/com.termux/files/usr/bin/bash
#
#
#
#colors
C='\033[1;36m'
G='\033[1;32m'                                           
R='\033[1;31m'                                           
Y='\033[1;33m'
B='\033[1;34m'
P='\033[1;35m'
RE='\033[0m'
#Colors                                                          
R='\033[1;31m' 
G='\033[1;32m' 
Y='\033[1;33m' 
B='\033[1;34m'
M='\033[1;35m' 
C='\033[1;36m'
W='\033[0m'
echo $(clear)
echo $(clear)                                                          
printf "$G" 
echo "      =============================="                             
echo "               __    __  __   "                                   
echo "               | |   \ \/ / "                                     
echo "               | |    \  /"                                       
echo "               | |___ /  \ "                                      
echo "               |_____/_/\_\ "                                     
echo                                                                    
echo "     Thanks for your teaching to Ivam3"                           
echo "      ====== By ___ Cinderella ======"                            
echo                                                                    
echo                                                                    
printf "$C\n"                                                           
echo "          [---] Join me on [---]"
echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
echo "      [-] t.me/Ivam3byCinderella [-]"
echo "            [-] t.me/ivam3 [-]"
printf "$R\n"
echo "          [---] README.md [---]"
printf "$W"
echo " This file will use install UPGRADE FT to .1.5"
echo
echo "     do not move or rename files in folder shell"
printf "$R\n"
echo "          [---] DISCLAIMER [---]"
printf "$W"
echo "   If the law is violated with it's use"
echo "     This would be the responsibility"
echo "        of the user who handled it"
printf "$R"
echo "       [-] Use At Your Own Risk [-]"
printf "$W\n"
printf "$C        Press$G ENTER$C to continue"
printf "$W\n"
read enter
echo $(clear) 
sleep 3
setterm -foreground green                                                           
	echo                                                            
	echo
	sleep 5
	cd $HOME
	sleep 10
	if [ -e ~/shell/shell ]; then
                printf "\n$C [!]$Y CORRECT . . .$G DONE!!!\n$W"
		echo
		cd $HOME
		sleep 5		
		chmod 777 shell/shell && chmod 777 shell/install
		sleep 7
        else
                printf "\n$C [W]$Y CORRECT . . .$G DONE!!!\n$W"
		echo
		sleep 5
		printf "$Y"
		echo " EL ARCHIVO fUE RENOMBRADO O YA FUE INSTALADO EXITOSAMENTE INTRODUCE FT PARA SU EJECUCION"
		echo
		sleep 15
		exit
        fi
	sleep 10
	echo $(clear)
	for i in  / - \ - \ - / - \ - / - \ - / - \ - / - \ -; do                       printf "$(clear)$Y [$G!$Y] $C INSTALANDO. . . .$i"
        sleep 1
done
echo
echo
if [ -e $PREFIX/bin/shell ]; then
                printf "\n$C [!]$Y CORRECT . . .$G DONE!!!\n$W"
		echo
		printf "$G"
		echo " ESTO ES PARA LOS QUE LA INSTALARON ANTERIORMENTE TODO PERFECTO SIN ERROR..."
		sleep 10
		cd $HOME
		sleep 5
		rm -r /data/data/com.termux/files/usr/bin/shell
        else
		echo
                printf "\n$C [W]$Y CORRECT . . .$G CORRECT!!!\n$W"
		echo
		printf "$G"
		echo " ESTO ES PARA LO QUE LA INSTALARON POR PRIMERA VEZ NO HAY ERROR.."
		sleep 5
        fi
	echo
	sleep 7
	pkg install util-linux
	echo
	termux-setup-storage
	echo
cd $HOME
sed -i "4a source $HOME/shell/shell" $PREFIX/etc/bash.bashrc
cp shell/shell /data/data/com.termux/files/usr/bin
rm -rf $PREFIX/usrc/etc/motd
sleep 10
echo
echo
if [ -e $PREFIX/bin/shell ]; then
                printf "\n$C [!]$Y DONE . . .$G INSTALLED!!!\n$W"
        else
                printf "\n$R [W]$Y FAILED . . .$R NO INSTALLED!!!\n$W"
        fi
	sleep 5
echo
echo
printf "$G"
echo " ::::::::::::: INSTALACION FINISHED ::::::::::::::::::"
echo " :::::::::::::::::::: BY LX ::::::::::::::::::::::::::"
echo "CIERRE Y ABRA NUEVAMENTE"
sleep 10
