#!/bin/bash
#NotFound
export ne='\033[1;30m'
export r='\033[1;31m'
export g='\033[1;32m'
export y='\033[1;33m'
export b='\033[1;34m'
export m='\033[1;35m'
export c='\033[1;36m'
export w='\033[0m'
#NotFound
trap ctrl_c 2
function ctrl_c() {
	echo
	printf "$r ESCRIBE exit PARA SALIR DE LA SHELL\n"
	reset
}
function reset {
	printf "$y$(pwd)$g \n"
	while printf "$w╭─$g Xploit@NotFound $g [$(date)]$w
╰──$r➤$g " i
read $i cm;do
case $cm in
	mash)
		printf "use sudo to enter into the root shell.\nuse actualizar to do pkg update && pkg upgrade.\nuse report to report bugs!.\nuse exit to exit the shell\n"
		reset
		;;
	clear)
		echo $(clear)
		banner
		reset
		;;

	sudo)
		sureset
		;;
	info)
		printf "$r CREATOR of SHELL $g TGD @TheGreenDash\n$r MODDER AND CREDIT TO $g LX\n https://t.me/Minattto\n"
		reset
		;;
	root)
		sureset
		;;
	actualizar)
		pkg update && pkg upgrade
		;;
	
	report)
		termux-open https://t.me/Minattto
		reset
		;;

esac
$cm
reset
done
}
function sureset {
	if [ -e $PREFIX/bin/sudo ]; then
	printf "$r$(pwd)\n$g"
	while printf "$w╭─$g Xploit@NotFound$r Root$w [$(date)]$w
╰──$r➤$g " i
read $i rt;do
case $rt in
	mash)
		printf 'use sudo to enter into the root shell.
		use actualizar to do pkg update && upgrade.
		use report to report bugs!
		use exit to exit the shell'
		;;
	info)
		printf "$r CREATOR $g TGD @TheGreenDash\n$r MODDER AND CREDIT TO $g LX https://t.me/Minattto\n"
		sureset
		;;
		

	sudo)
		reset
		;;
	actualizar)                                                    
		pkg update && pkg upgrade
		;;                                                     
	report)
		termux-open https://t.me/joinchat/K7ViO1VAPWqcIotTL_g0Zw
		sureset
		;;
	exit)
		exit
		;;
esac
sudo $rt
sureset
	done
elif [ -e $PREFIX/home/termux-sudo/sudo ]; then
	cd $HOME/termux-sudo && cp sudo $PREFIX/bin
	printf "$g ERES USUARIO ROOT\n"
	sureset
else
	printf "$r Oops!!! NO ERES USUARIO ROOT!!!\n"
	reset
fi

}

function banner {
printf "$g

                                                           
                         ,**. ,,.                          
                          *.******.                        
                          .*  /*, /,                       
                 ,/**,.***..*, ./* .*,                     
           .*/*****   */  ,/***  ,*  ,*.                   
           ,**                 ,   ,   **,                 
       ***,                              **,               
       ,*/                                 ./*             
    .,*,         ,/**,,,,,**/*                /,           
    */*       .*,             .,**             ,*.         
     ,/       *.                 .**        $r,.$g  ./,        
   .**       *,                    .*/        $r.$g   /,       
   ,***.     /,                      ,/.           **.     
     ./      .*.                       ,/*         /,      
     *,       .*.                        .*/.       **.    
    .,/*/.      **.                         .,/.      ./*. 
        */        **,                          */       ** 
        .*****       **,.                       ,/     .*. 
             .*/.       */*,                    .*.   /*   
                .,*/.       ,**,.               ,*//*.     
                    .,**.       ,/*.                       
                         .,//,     ./*.                    
                             .,/*.    /*                   
$w"
printf "$r
 _   _       ____            _            _    $g     _          _ _$r
| \ | |     |  _ \ ___ _ __ | |_ ___  ___| |_ $g  ___| |__   ___| | |$r
|  \| |_____| |_) / _ \  _ \| __/ _ \/ __| __|$g / __|  _ \ / _ \ | |$r
| |\  |_____|  __/  __/ | | | ||  __/\__ \ |_ $g \__ \ | | |  __/ | |$r
|_| \_|     |_|   \___|_| |_|\__\___||___/\__|$g |___/_| |_|\___|_|_|$r
$g By TEAM-NOT-FOUND
use 'mash' to list the manual - use 'info' or use 'report' for errors
"
echo
sleep 1
}
banner
reset
